-- Run this in your Supabase SQL Editor to create the necessary tables

create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id text not null,
  user_email text,
  service_id text,
  title text,
  price numeric,
  date text,
  time text,
  address text,
  status text default 'Upcoming',
  image text
);

-- Simply disable RLS for now to ensure inserts work without complex auth setup
alter table public.bookings disable row level security;
